### ISSUE TITLE
Possible to autodetect if Horizon is installed?

### ISSUE THREAD

**Issue by Arkhorse** [kinggath/WorkshopFramework#55]
The purpose of this is to remove the need to patch the new settler records. Since Horizon removes most of their inventory.

**Comment by kinggath** [comment]
@Arkhorse My apologies for the long delay, you had posted this right around the release of SS2, so I was a bit overwhelmed.

Does Horizon edit the default settler records? If so, WSFW shouldn't impact that since WSFW just creates a wrapper around the leveled list of the default settlers.

If you're finding it does impact that, I can definitely add Horizon to the list that causes WSFW to ignore its own settler lists.

**Comment by Arkhorse** [comment]
> @Arkhorse My apologies for the long delay, you had posted this right around the release of SS2, so I was a bit overwhelmed.
> 
> Does Horizon edit the default settler records? If so, WSFW shouldn't impact that since WSFW just creates a wrapper around the leveled list of the default settlers.
> 
> If you're finding it does impact that, I can definitely add Horizon to the list that causes WSFW to ignore its own settler lists.

Yeah, I know it was a busy time. wanted to post this before I forgot about it...
I dont know exactly how Zaw does it, but he does change all settlers inventory to contain only a settler pistol and clothing.
There is a patch here (4th file) https://www.nexusmods.com/fallout4/mods/36096?tab=files

**Comment by kinggath** [comment]
Looks like the only thing that file edits is the vendor production, so I'm guessing its not conflicting with the settler records. redbaron reported that field as well, so I'll close this ticket and use his to deal with that problem.
