### ISSUE TITLE
WorkshopScript CapMaxNPCsByBedCount

### ISSUE THREAD

**Issue by msalaba01** [kinggath/WorkshopFramework#85]
In this Function on WorkshopScript
https://github.com/kinggath/WorkshopFramework/blob/affc4fa356292e356cb518784f8e31ad331511fd/Scripts/Source/User/WorkshopScript.psc#L2018-L2039
If we are using bed count as a population cap, shouldn't iMaxNPCs always = the settlement bed count?
```
	if(WSFW_Setting_CapMaxNPCsByBedCount.GetValue() == 1)
		iMaxNPCs = GetBaseValue(Beds) as Int
	endif
```

**Comment by kinggath** [comment]
If the player also has Charisma limit enabled, then we acknowledge that as well. So the logic currently is:

- First accept a hard override set by a mod. 
- Next check charisma limit
- Finally, check bed count, if charisma limit is greater than the bed count, cap at bed count - otherwise use charisma limit (which will be less than the bed count)

This is what made most logical sense to me to allow for acknowledging both settings - effectively this logic is always choosing the lesser of the two. If someone wants one or the other to be the method, they can turn one off.
