### ISSUE TITLE
Water Production only produces 9 Purified Water

### ISSUE THREAD

**Issue by calebwestdev** [kinggath/WorkshopFramework#91]
I set up my water farm as I usually do and only got 9 Purified Water multiple times, no there are absolutely no other "Aid" items in my workbench, that all gets stored elsewhere (I'm experienced at water farming)

I have 160 water production, and 5 settlers (The default sanctuary settlers from concord/the minutemen), I have no other settlements linked to sanctuary either

I've seen this issue brought up elsewhere:
https://simsettlements.com/site/index.php?threads/bug-workshop-framework-seems-to-screw-with-surplus-resources.9934/

I have the latest version of workshop framework installed
The reason I installed it is because before I was trying out sim settlements 2 but decided it wasn't for me at the moment so I started a new game with it uninstalled and forgot to uninstall workshop framework (I assume it's unsafe to uninstall)

**Comment by kinggath** [comment]
The base game scripts have a max water storage system in place. The formula is this:

int maxStoredWaterBase = 5 const
float maxStoredWaterPerPopulation = 0.25 const

maxStoredWaterBase + (iPopulation * maxStoredWaterPerPopulation)

Unfortunately, Bethesda failed to actually cap production to it, and instead allow one time for the water to WAY overproduce - then the next day nothing would produce unless the player looted it. So for example, max storage would be 6 - and so long as the settlement had less than 6, it would produce the full 160, instead of up to the 6 max storage.

We corrected this bug with Workshop Framework.

(The fact that you get 9 is because WSFW increased the max default storage to handle rare cases where script lag causes the settlers to consume water before the game produces more for them)

I am aware of an issue with food production and hope to have it resolved soon, as I finally have a decent lead on the issue!
