### ISSUE TITLE
WorkshopObjectScript UFO4P_ValidateDamageHelperRef

### ISSUE THREAD

**Issue by msalaba01** [kinggath/WorkshopFramework#94]
This is most likely a UFO4P issue, but since WSFW is forwarding the fixes, I'll bring it to your attention.
https://github.com/kinggath/WorkshopFramework/blob/60524f68f874a438fafbc6133b5f0cbf9af09534/Scripts/Source/User/WorkshopObjectScript.psc#L1036-L1074
I think the way this is written could cause a rare chance to cause an issue:
```
	ObjectReference myDamageHelperLinkedRef = myDamageHelperRef.GetLinkedRef()
	if myDamageHelperLinkedRef && myDamageHelperLinkedRef == self
		return
	else
		WorkshopParent.wsTrace(self + "	UFO4P_ValidateDamageHelperRef - myDamageHelperRef not linked to me; relinking")
		myDamageHelperRef.SetLinkedRef(self)
	endIf
```
if `myDamageHelperRef` is none, this will try to set a linked ref and later in the code, a new one will be spawned leaving myDamageHelperRef orphaned and enabled.
To me, it should be:
```
	ObjectReference myDamageHelperLinkedRef = myDamageHelperRef.GetLinkedRef()
	if myDamageHelperLinkedRef
		if myDamageHelperLinkedRef != self
			WorkshopParent.wsTrace(self + "	UFO4P_ValidateDamageHelperRef - myDamageHelperRef not linked to me; relinking")
			myDamageHelperRef.SetLinkedRef(self)
		endif

		return
	endIf
```

**Comment by kinggath** [comment]
That code is inside of an "if myDamageHelperRef, which would fail if it was none. 

If you're thinking the myDamageHelperLinkedRef could be none, that's OK, because the next block of code is linking myDamageHelperRef, not myDamageHelperLinkedRef, and we know that myDamageHelperRef is not None at this point. It's confusing to look at because the two vars have similar names:

myDamageHelperRef
myDamageHelperLinkedRef
